contest-questions APIs
Cyber-Labs/cl-judge pull request #84
Opened 2020-12-19 05:33 UTC by ridhishjain

#### Issue at work: #60 

#### APIs:
* *`addQuestion`*
**`POST /contests/:contest_id/:questions` Moderator only**: Add question

* *`removeQuestion`*
**`DELETE /contests/:contest_id/questions` Moderator only**: remove question

* *`getAllQuestions`*
**`GET /contests/:contest_id/questions`**: accessible to all, if public contest otherwise to group members

* *`getQuestion`*
**`GET /contests/:contest_id/questions/:question_id`**: accessible to all, if public contest otherwise to group members

* *`getLeaderboard`*
**`GET /contests/:contest_id/leaderboard` All participants**: everyone eligible for the contest should be allowed

* *`getQuestionLeaderboard`*
**`GET /contests/:contest_id/questions/:question_id/leaderboard`**: accessible to all, if public contest otherwise to group members

2020-12-22 08:17 UTC, cjchirag7 requested changes
While returning the questions of a contest, make sure that a normal user is not able to see the questions before the contest.

2020-12-22 08:17 UTC, cjchirag7 commented on server/models/contests/getQuestion.js
> +        WHERE ug.username = ? AND cg.contest_id = ?)))`,
```suggestion
      `SELECT q.name, q.difficulty, q.type, max_score, q.creator, q.problem_statement, q.input_format, q.output_format, q.constraints, q.options FROM contests_questions cq
      INNER JOIN contests c ON c.id = cq.contest_id
      INNER JOIN questions q ON cq.question_id=q.id
      WHERE (c.id=? AND q.id=?) AND (EXISTS(SELECT 1 from contests_moderators WHERE contest_id=? AND moderator=?) OR (NOW()>c.end_time AND c.confidential_questions=0 AND (c.public = 1
      OR EXISTS(SELECT 1 FROM contests_groups cg INNER JOIN user_groups ug ON cg.group_id = ug.group_id 
        WHERE ug.username = ? AND cg.contest_id = ?))) OR (NOW()>=c.start_time AND NOW()<=c.end_time AND EXISTS(SELECT 1 FROM contests_participants WHERE contest_id=? AND participant=?)))`,
```

2020-12-22 08:17 UTC, cjchirag7 commented on server/models/contests/getQuestion.js
> +      [questionId, username, contestId],
```suggestion
      [contestId, questionId, contestId, username, username, contestId, contestId, username],
```

2020-12-22 08:17 UTC, cjchirag7 commented on server/models/contests/getQuestion.js
> +            'The contest is private and user do not belongs to any eligible groups'
```suggestion
            'You do not have moderator access of the contest. If the contest is active, make sure that you are registered as a participant.'
```

2020-12-22 08:17 UTC, cjchirag7 commented on server/models/contests/removeQuestion.js
> +              'Invalid question Id or the user do not have required permissions'
```suggestion
              'Invalid question Id or you do not have moderator access to the contest'
```

2020-12-23 05:38 UTC, ridhishjain commented on server/models/contests/getAllQuestions.js
> +        WHERE ug.username = ? AND cg.contest_id = ?))`,
got it

2020-12-23 06:06 UTC, cjchirag7 approved these changes
LGTM!

2020-12-23 06:07 UTC, ridhishjain commented
dont merge I'm still checking the queries

2020-12-26 07:49 UTC, NBNARADHYA requested changes
Just some changes, everything else LGTM!

2020-12-26 07:49 UTC, NBNARADHYA commented on server/models/contests/removeQuestion.js
> +      `DELETE FROM contests_questions WHERE question_id = ? AND contest_id = (SELECT contest_id FROM contests_moderators WHERE contest_id=? AND moderator=?)`,
I think it is better to use either `EXISTS` or `JOIN` which execute much faster
```suggestion
      `DELETE FROM contests_questions WHERE (SELECT 1 FROM contests_moderators WHERE contest_id=? AND moderator=?) AND question_id = ? AND contest_id = ?`,
```

2020-12-26 07:49 UTC, NBNARADHYA commented on server/models/contests/removeQuestion.js
> +      `DELETE FROM contests_questions WHERE question_id = ? AND contest_id = (SELECT contest_id FROM contests_moderators WHERE contest_id=? AND moderator=?)`,
Or use `JOIN` like this:
```suggestion
      `DELETE cq FROM contests_questions cq INNER JOIN contests_moderators cm ON cm.contest_id = cq.contest_id  WHERE cm.moderator = ? AND cq.question_id = ? AND contest_id = ?`,
```

2020-12-26 07:49 UTC, NBNARADHYA commented on server/models/contests/removeQuestion.js
> +      [questionId, contestId, username],
For `EXISTS`
```suggestion
      [contestId, username, questionId, contestId],
```

2020-12-26 07:49 UTC, NBNARADHYA commented on server/models/contests/removeQuestion.js
> +      [questionId, contestId, username],
For `JOIN`:
```suggestion
      [username, questionId, contestId],
```

2020-12-27 08:22 UTC, NBNARADHYA requested changes

2020-12-27 08:22 UTC, NBNARADHYA commented on server/models/contests/removeQuestion.js
> +      `DELETE FROM contests_questions WHERE (SELECT 1 FROM contests_moderators WHERE contest_id=? AND moderator=?) AND question_id = ? AND contest_id = ?`,
I actually meant to say this: I forgot `EXISTS`, i have now updated
```suggestion
      `DELETE FROM contests_questions WHERE EXISTS(SELECT 1 FROM contests_moderators WHERE contest_id=? AND moderator=?) AND question_id = ? AND contest_id = ?`,
```

2020-12-27 15:29 UTC, NBNARADHYA approved these changes
LGTM!

2020-12-27 20:19 UTC, merged